### GET /

GET http://localhost:6439

### Register a  user POST  /auth/register

POST http://localhost:6439/auth/register
Content-Type:application/json

{
    "username": "gaurav123",
    "password": "123123123"

}


### login a user POST /auth/login

POST http://localhost:6439/auth/login
Content-Type:application/json
  
{
    "username": "gaurav123",
    "password": "123123123"

}

